package com.fis.ais.riva.activity;

public enum ActivityAction {
    SESSION_CREATED,
    CASE_INVESTIGATION_STARTED,
    CASE_DATA_FETCHED,
    CASE_DATA_FETCH_FAILED,
    LLM_STREAM_COMPLETED,
    LLM_STREAM_INTERRUPTED,
    LLM_STREAM_FAILED,
    CHAT_MESSAGE_SENT,
    CHAT_HISTORY_VIEWED
}
